services:
  db:
    image: mysql:8.0
    container_name: wallet-mysql
    environment:
      MYSQL_DATABASE: wallet_db
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_0900_ai_ci" ]
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-proot" ]
      interval: 5s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7.4
    container_name: wallet-redis
    command: >
      redis-server
      --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - TZ=Asia/Bangkok
    restart: unless-stopped

volumes:
  redis-data:

#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: wallet-api
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      DB_URL: jdbc:mysql://db:3306/wallet_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      DB_USER: app
#      DB_PASSWORD: app
#    ports:
#      - "8080:8080"
